// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// run_sodi_rcpp
List run_sodi_rcpp(DataFrame init, List parms, bool progress);
RcppExport SEXP sodi_run_sodi_rcpp(SEXP initSEXP, SEXP parmsSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    DataFrame init = Rcpp::as<DataFrame >(initSEXP);
    List parms = Rcpp::as<List >(parmsSEXP);
    bool progress = Rcpp::as<bool >(progressSEXP);
    List __result = run_sodi_rcpp(init, parms, progress);
    return Rcpp::wrap(__result);
END_RCPP
}
