// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// run_sodi_rcpp
int run_sodi_rcpp(DataFrame init, List parm, bool progress, CharacterVector file);
RcppExport SEXP sodi_run_sodi_rcpp(SEXP initSEXP, SEXP parmSEXP, SEXP progressSEXP, SEXP fileSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        DataFrame init = Rcpp::as<DataFrame >(initSEXP);
        List parm = Rcpp::as<List >(parmSEXP);
        bool progress = Rcpp::as<bool >(progressSEXP);
        CharacterVector file = Rcpp::as<CharacterVector >(fileSEXP);
        int __result = run_sodi_rcpp(init, parm, progress, file);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
