# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
run_sodi_rcpp <- function(init, parm, progress, file) {
    .Call('sodi_run_sodi_rcpp', PACKAGE = 'sodi', init, parm, progress, file)
}

